### ISSUE TITLE
Linux WebGPU initialization failure is not propagated upwards

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#1038]
Linux Chrome doesn't support WebGPU in totality yet, but still registers a `gpu` object, which means the runtime attempts to initialize. Unfortunately, this fails and the error is not propagated upwards, so it is indefinitely "Loading" with the only sign of trouble in the web console.

We should do one or both of these things:
- [x] change web embed to check for Linux and fail fast before initialization
- [x] propagate errors in initialization to the web embed, so users know that there are failures in that step

**Comment by ten3roberts** [comment]
Error are propagated from `AppBuilder::build` to the instance manager.

I did that in the merge of `init` and `start` last week, where the whole `start` function returns an error if `AppBuilder::build` failed, and that works properly.

The issue is that the Gpu initialization just unwraps in the asset cache and doesn't return an error at all.

Fixing it
