### ISSUE TITLE
Text doesn't update when `text()` is updated via `set_component`

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#113]
I'm trying to update the text in response to the number of strokes changing in the minigolf gamemode. Unfortunately it doesn't seem to work.

**Comment by SK83RJOSH** [comment]
Quick update on this issue, the text *is* updated for clients that join after it's been changed. So this is likely a missing system, or a bugged query.

**Comment by philpax** [comment]
Other debugging notes: the relevant systems do run, but the GPU isn't updated?

**Comment by SK83RJOSH** [comment]
Seems to be the case; I couldn't debug much further but at the very least the mesh component seemed to be updated.

**Comment by MischaU8** [comment]
For the minigolf example the player user_id label gets mangled after a couple shots. This happens both for the local player as well for others joining the game. This behavior seems related to the text update, since it doesn't happen when I comment out line https://github.com/AmbientRun/Ambient/blob/main/guest/rust/examples/minigolf/src/lib.rs#L355
```
entity::set_component(player_text, text(), stroke_count.to_string());
```

<img width="912" alt="Screenshot 2023-02-28 at 11 45 26" src="https://user-images.githubusercontent.com/99098079/221833100-2d3eeaf8-f5e6-4d08-b5f4-1767e7807382.png">

Ambient 0.1.1 installed via git on OSX (M1)

**Comment by philpax** [comment]
Ah thanks, that's a semi-known issue. I've just created an issue to track it 😅
