### ISSUE TITLE
Helmy

### ISSUE THREAD

**Issue by Busuami** [AmbientRun/Ambient#179]

**Comment by RouisIbra** [comment]
I hope this is a joke, if it is not a joke, please provide more info about the issue. If you found a security vulnerability contact the developers by Email. If something isn't working for you and you believe it is not because of the library, make sure to ask in the discussion and the community will help you. Also according to the government rule 685 it is illegal to laugh so you might have just committed a crime in this website. If you have any complains contact the government at gov@gove.gov

**Comment by MavethGH** [comment]
Can you elaborate?

**Comment by philpax** [comment]
I'll reopen this if more detail is provided.
