### ISSUE TITLE
Add helpers for 3D scene querying

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#283]
i.e. `world_to_screen`, `screen_to_world_direction`, `screen_ray`.

We already have `screen_ray`, so shouldn't be too hard to implement. Should we do this in the host or in the guest code?

**Comment by owenpalmer** [comment]
Hey! I wouldn't mind giving this a shot, since it directly relates to my game, and I would love to learn more about how the api works!

**Comment by philpax** [comment]
Awesome! I'm planning on writing up some documentation about how the WIT stuff works, but in the meantime, you can poke around the commits for the `wit` folder: https://github.com/AmbientRun/Ambient/commits/main/crates/wasm/wit

Basically, all of the core function definitions happen there; the host build script will automatically generate bindings on the host and guest. You'll then need to implement the corresponding traits on the host (just follow the errors) and write wrapper functions on the guest.

Let me know if you need a hand - I'm hoping to get more detailed docs written soon!

**Comment by owenpalmer** [comment]
Thanks for the info @philpax! Just to get familiar with the process of exposing _**anything**_ to the api, I duplicated the [`get_raw_input`](https://github.com/AmbientRun/Ambient/blob/59aaf3cc1c99181f84b625c85a42d1e950ce05ee/crates/wasm/src/client/implementation.rs#L49) function (keeping the same fn body and return type, just to see how the process works), created a new wit definition, and ran the build script which successfully generated the bindings. I wrote the guest wrapper function, and successfully called the function from the API in Puckle! So I at least know how to expose a function :)

I have a few questions to find the right mental model of how this finalized implementation should work.

1. Would it make sense to expose the existing [`screen_ray`](https://github.com/AmbientRun/Ambient/blob/59aaf3cc1c99181f84b625c85a42d1e950ce05ee/crates/core/src/camera.rs#L302) function by simply calling it from the new host trait implementation (i.e if new `screen_ray` was implemented [here](https://github.com/AmbientRun/Ambient/blob/59aaf3cc1c99181f84b625c85a42d1e950ce05ee/crates/wasm/src/client/implementation.rs#L48))? Or should I completely move the function from `camera.rs` to the new trait implementation?
2. Does it make sense to expose `screen_ray` as a camera helper function similar to `get_raw_input`?
3. `screen_ray` returns the [`Ray`](https://github.com/AmbientRun/Ambient/blob/59aaf3cc1c99181f84b625c85a42d1e950ce05ee/crates/std/src/uncategorized/shapes/mod.rs#L260) type. Is there anything specific I should know about exposing a type and making it a return type of an exposed function?
4. Idea: while we're on the topic of rays, what if `raycast` took a `Ray` as an argument rather than two `Vec3`s? Just a thought :P

Thanks for the help :)

**Comment by owenpalmer** [comment]
Hey @philpax! Thank you for that very helpful comment! I've made considerable progress and I've committed [here](https://github.com/owenpalmer/Ambient/commit/b2b9a485126be15f4e71132a2e80f41ab88b40ac) what I have so far. I would like to get some advice before I make a PR. I'll clean up and redo the commits once I have a fully working version.

The `Ray` type wit record declaration is in types.wit, and the guest `Ray` struct declaration is in `mod.rs`. Is there a better place to put these? I'm not entirely sure how the wit types should be organized.

`screen_ray` is exposed, but I'm currently only returning a test `Ray`. Do you have any advice on how I should be getting the world/camera/input data? How many of those should be passed as arguments? I'm currently a little unfamiliar with the host ecs api, so I'd appreciate any help.

Any tweaks/advice/feedback you have would be very apricated. I've learned a lot already!

**Comment by philpax** [comment]
Awesome! Happy to see it :)

> The Ray type wit record declaration is in types.wit, and the guest Ray struct declaration is in mod.rs. Is there a better place to put these? I'm not entirely sure how the wit types should be organized.

Living in `types.wit` is fine - that's where the types that are shared between modules live. As this will be shared between `camera` and `physics`, it seems reasonable to me to keep it there. We can revisit this later on if needed.

`mod.rs` is also reasonable by the same kind of reasoning. That being said, I'd suggest moving it to a `shapes.rs`. Over time, we can start to duplicate some of the functionality on the host, including sphere/plane/AABB intersection etc: https://github.com/AmbientRun/Ambient/blob/main/crates/std/src/uncategorized/shapes/mod.rs

(You don't need to do that now, but we can add to it later. With that being said, you may still find it useful to do, especially for doing raycasts in Puckle without using physics)

> screen_ray is exposed, but I'm currently only returning a test Ray. Do you have any advice on how I should be getting the world/camera/input data? How many of those should be passed as arguments? I'm currently a little unfamiliar with the host ecs api, so I'd appreciate any help.

Sure! The `Bindings` struct contains a reference to the `World` in `world_mut()`; you can use this to interact with the host's ECS. `World` has methods for interacting with the ECS; they should be pretty self-explanatory. We've also been slowly aligning it to match the guest API, so hopefully it doesn't come as too much of a shock.

For getting access to the actual data itself, I'd look around at how the existing code in `client_game_state` etc works. It's all one ECS world (at least in this area of the code - there's a UI ECS that's responsible for state/rendering between games, but you don't need to worry about that).

**Comment by owenpalmer** [comment]
Thanks for the info! I've made a few commits on my [screen-ray branch](https://github.com/owenpalmer/Ambient/tree/screen-ray) and implemented `screen_ray` (essentially copying snippets from client_game_state.rs), and exposed the `Ray` type. I also added a guest example. I'm very close to completion, but I would appreciate some insight into a few issue's I'm having.
1. My example demonstrates the bug in the screen_ray function
![2023-04-13 23-12-28](https://user-images.githubusercontent.com/67305498/231960137-ca4632ed-599a-4475-b264-f99b352c3683.gif)
The screen_ray is doing a raycast hit with a plane collider. The ray seems to be slightly inaccurate most of the time, except sometimes it will "randomly" be accurate for a split second. Weirdly enough, this sort of "randomness" still happens if you pass a fixed `Vec2::ONE` (for example) into screen_ray, showing that it's not an input problem. I also noticed that if the screen size is completely square, the screen_ray is always correct.

2. Currently, I'm error handling in the screen_ray implementation with `.context("error message")?`. It looks to me that sometimes the client loads before an active camera is set, resulting in screen_ray panicking [here](https://github.com/owenpalmer/Ambient/blob/0f8aa0daed51592a193033c167aff93a00e0222d/crates/wasm/src/client/implementation.rs#L88).

As always, your help is appricated :)

**Comment by philpax** [comment]
1) Hmm, not sure - seems like it could be an issue with the aspect ratio not being accounted for somewhere, but I don't see anything immediately wrong. On a semi-related note, is there a reason for reimplementing instead of calling this? https://github.com/AmbientRun/Ambient/blob/6f577abab293734929153e9c6339320dbbeb38e4/crates/core/src/camera.rs#L131-L139

   You may also find it useful to expose these functions, or something similar: https://github.com/AmbientRun/Ambient/blob/6f577abab293734929153e9c6339320dbbeb38e4/crates/core/src/window.rs#L13-L20

   (I'd say do this in the WIT, so other guests can benefit; the latter one could be exposed as a helper function on `PlayerInput`)

2) Yeah, that error handling is fine for now - I need to go through and convert them to actual error variants (#236). For now, you can just move the camera creation to the client 😅 - I'd also suggest perhaps taking a `Option<EntityId>` as the first argument as the camera to use, and if not specified, default to the player's active camera.

**Comment by owenpalmer** [comment]
>On a semi-related note, is there a reason for reimplementing instead of calling this?

Yep, that was just a temporary implementation to get it working. Turns out `ambient_core::screen_ray` is either broken or it doesn't work the way I'd expect. The ray it returns doesn't seem to be right. Just to see, I copied the `client_game_state.rs` implementation to `ambient_core::screen_ray` and then it works, as seen in my [example](https://github.com/owenpalmer/Ambient/tree/screen-ray/guest/rust/examples/basics/screen_ray). Here's the commit: https://github.com/owenpalmer/Ambient/commit/3c678a252d9b4afd54e6dc964101631abd87c398

`ambient_core::screen_ray` only seems to be used here: https://github.com/owenpalmer/Ambient/blob/screen-ray/crates/input/src/picking.rs#L53
Are we sure that picking.rs was/is always working?

>I'd also suggest perhaps taking a Option<EntityId> as the first argument as the camera to use

Good idea, I got `EntityId` to work, and I'll wrap it in `Option` later.

Also, somewhere along the way I fixed the aspect_ratio bug I showed in the gif :)

**Comment by owenpalmer** [comment]
>On a semi-related note, is there a reason for reimplementing instead of calling this?

Yep, I was having an issue with `ambient_core::screen_ray`, so that was just a temporary implementation to get it working. Turns out the problem was that `ambient_core::screen_ray` returns a ray that points opposite of what I would expect.

Right now I'm just reversing the direction in the host impl: https://github.com/owenpalmer/Ambient/commit/ba4b0c5aa5b4e8a79cd0c272ef2b89c0e6533060
Let me know if there's a preferable alternative to this ^ .

I've updated the example to initialize the camera client side, and the aspect ratio bug I displayed in the gif earlier has been solved at some point along the way :)

I'm opening a PR just to see if we can get screen_ray merged. I can revisit this later to expose more functions.

**Comment by philpax** [comment]
I'm going to add `camera::screen_to_clip_space` soon to help with the NDC conversion

**Comment by philpax** [comment]
All that remains is `screen_to_world_direction` (which I think is the composition of `screen_to_clip_space` and `screen_ray`... which should probably be called `clip_space_ray`, now that I think about it) and `world_to_screen`.

**Comment by owenpalmer** [comment]
Sure!
- [ ] rename screen_ray to clip_space_ray
- [ ] add world_to_screen
- [ ] add screen_to_world_direction

Would `screen_to_world_direction` automatically use the client cursor position to get the screen_ray? In that case, would it make sense to call it something like `mouse_to_world_direction`?

**Comment by philpax** [comment]
Nah, not necessarily - you could pass in non-mouse coordinates (e.g. rendering something 3D underneath some UI)

Otherwise, sounds good to me!

**Comment by owenpalmer** [comment]
Cool, that makes sense 👍

**Comment by philpax** [comment]
Yep, that's everything, thanks!
