### ISSUE TITLE
#[main] macro fails to expand for rust-analyzer

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#307]
This is what a new project on master looks like when opened with vscode:

![Screenshot 2023-04-13 at 15 22 43](https://user-images.githubusercontent.com/1288009/231772087-f1fdb035-1d60-4eb7-a554-37851a80b1b1.png)

**Comment by philpax** [comment]
I've been looking into this for a bit and I'm pretty sure it's because there are no binaries in the project that depend on `ambient_api` by itself with no features (as opposed to the `client` and `server` binaries, which depend on `ambient_api` with their corresponding features), so the macro is never built. Looking into potential fixes...
