### ISSUE TITLE
Ambient API v0.2.0 documentation build fails on docs.rs

### ISSUE THREAD

**Issue by mebyz** [AmbientRun/Ambient#369]
**problem :** 

Ambient v0.2.0 has just been released but the API documentation fails to build and is not accessible as predicted on https://docs.rs/ambient_api/0.2.0/ambient_api/

**hints:**

it seems that this commit from March 2th

https://github.com/AmbientRun/Ambient/blame/6d8ec36162cb51787d62d6ebe7deb43ecb9008d6/guest/rust/api_core/src/internal/mod.rs#L23 

introduces wit::__link_section dependency on line 23

which apparently results in an error on the API documentation build workflow as seen in the logs here

https://docs.rs/crate/ambient_api/0.2.0/builds/808933

it seems to be broken just after 0.1.1 in the first 0.2.0 RCs

**Comment by mebyz** [comment]
i think we may have to add this/these dependency-ies to rust-lang/crates-build-env itself as mentioned here : 

https://github.com/rust-lang/crates-build-env#adding-new-dependencies 

=> to be done : create an issue, submit a PR on rust-lang/crates-build-env that adds the dependencies to linux/packages.txt

so that crates can take it into account during the build

proposed list of packages to be added : 

wit-bindgen-core = "0.6.0"
wit-bindgen-rust = "0.6.0"
wit-component = "0.8.1"

as seen in https://github.com/AmbientRun/Ambient/blob/6d8ec36162cb51787d62d6ebe7deb43ecb9008d6/Cargo.toml#L152

right ?

**Comment by philpax** [comment]
Thanks for reporting this! The packages were a red herring; the issue was that the API docs were being built for non-WASM platforms, when they weren't before. This is likely because this version of the API includes crates from the host.

I've fixed this and cut a new release to fix the docs, which are now all up: https://docs.rs/ambient_api/latest/ambient_api/

Appreciate the investigatory work you did in the meantime :)
