### ISSUE TITLE
Unify names of physics colliders and primitives

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#396]
At present, the physics colliders and primitives have slightly different names, which is a bit odd:

`core::primitives::cube` vs `core::physics::box_collider`
`core::primitives::quad` vs `core::physics::plane_collider`

This issue would be good for someone who wants to get familiar with how components are defined on the host.

**Comment by awtterpip** [comment]
i'm not entirely sure how github issues works so im not sure if i did this correctly, but i believe i have fixed this with #407

**Comment by FredrikNoren** [comment]
@awtterpip So we shouldn't call it `quad_collider`, because a quad and a plane are different things; a plane is an infinite surface, whereas a quad is a "small" rectangle.

In general, `core::primitives::quad` and `core::physics::plane_collider` are two different things. We could rename `core::primitives::quad` to `core::primitives::plane`, but it would still be a different thing from the collider (one infinite, one not).

For cube and box, I'd suggest naming them both cube.

**Comment by awtterpip** [comment]
@FredrikNoren so to clarify, we want to keep quad and plane_collider as they are?

**Comment by philpax** [comment]
Done - thanks @awtterpip! 🚀
