### ISSUE TITLE
Text rendering of zero sized meshes broken

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#424]
@VinhTruongAmbient

**Comment by philpax** [comment]
Is this related to #183 ?

**Comment by VinhTruongAmbient** [comment]
This issue is related to https://github.com/AmbientRun/Ambient/pull/393 where I validated meshes. However this PR introduced a subtle bug here:
https://github.com/AmbientRun/Ambient/blob/main/crates/text/src/lib.rs#L412-L415
It is possible for text code to generate a mesh with no vertices. I don't know yet why this happens, but I feel like this should not happen in the first place.

**Comment by FredrikNoren** [comment]
@VinhTruongAmbient Think it does that when there are 0 characters in the text
