### ISSUE TITLE
Hide logging output by default

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#459]
It's getting really noisy when starting ambient now. I think it's time that we add a `--verbose` or `--logging` flag, and only output what a user prints with `println` from with the scripts by default + "use `ambient join eu.proxy.ambient.run:9165` to join". We could also utilize temporary console lines while the project is building (i.e., showing "Building asset/..." while it's building, but then removing that line).

**Comment by ten3roberts** [comment]
I am quite familiar with how the logging setup works at the moment, so I could see myself doing this.

Additionally, I think that we shoud remove the fallback log directives which silent some specific crates, so that `RUST_LOG=info` does show infos for e.g `ambient_gpu`. This behavior has shot us in the foot a few times and is quite a surprising behavior as you get the false premise that you now have all logs of info level.

I think removing this and having a `--verbose` flags will increase consistency and make the overall user experience better.

Furthemore, there are some amount of logs in the server modules, and they will be addressed in the #421 PR

**Comment by philpax** [comment]
100% agreed with this. I cleaned up the logs earlier, but INFO logs keep finding their way into the codebase. I'm fine with removing the per crate silencing if we're much more judicious about what we log by default.

**Comment by ten3roberts** [comment]
Should we use tracing and be more judicious with our log levels, like using `debug` for most spammy stuff rather than doing `info` for everything, and then selectively silencing `info`?

For user facing messages we could just use `eprintln` or `println`.

What do you think?
