### ISSUE TITLE
'run' command line syntax differs from Rust workspaces

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#500]
UPDATE

`cargo run -p subproject` is the command used by cargo

`ambient run subproject` is the command used by ambient for the same workspace behaviour

`ambient run -p subproject` could either work as expected, or give a better warning. currently it just says `-p` is an invalid argument without indicating correct syntax

-----

ORIGINAL TEXT

I'd like to use Rust/Cargo [workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) in order to run multiple projects within one build target (to save space on local machine)

`cargo run -p subproject` does not work, see error message:

```
PS C:\Users\hi\RustProjects\09-ambient-workspace> cargo run -p world
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: client_world, server_world
```

And, `ambient run -p subproject` is not supported.

(cc @FredrikNoren we discussed this a couple weeks ago)

**Comment by droqen** [comment]
@FredrikNoren Oh hell yeah! I should have tried that since it's what the examples use. It works.

Would be good for `-p` to work as well for people coming from Rust, or at least have a custom warning for that case.

**Comment by philpax** [comment]
Hm, I'm not sure I see a good way in `clap` (our argument parser) to make the `path` setting both positional (as it is now) and named. The three options I can see are:
- Accept `-p` as a flag, do nothing
- Accept `-p` as a flag, warn that it was used and has no semantic meaning
- Remove the positionality and always make it accessible through `-p` (e.g. you would have to do `ambient run -p project` always instead of `ambient run project`, but `ambient run` if you're in the same folder would work as normal)

Which of these would you prefer?

**Comment by droqen** [comment]
Hmm. Because I'm used to it now and it's nice to not need those three extra keystrokes my preference would be "Accept `-p` as a flag, warn that it was used and has no semantic meaning". With the added detail that it would be nice to say the alternative does exist; warn that it was used, has no semantic meaning, **and** that `ambient run path` might be what the user is looking for rather than `ambient run -p path`
