### ISSUE TITLE
Mismatched network versions should fail hard by default

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#560]
When you connect to a server, the following check occurs and prints a log:
```rust
let current_version = get_version_with_revision();

if server_info.version != current_version {
    tracing::error!(
        "Client version does not match server version. Server version: {:?}, Client version {:?}",
        server_info.version,
        current_version
    );
}
```

However, this doesn't actually stop the connection from proceeding, which means that you can connect to a server with the wrong protocol version when you share the same base version (e.g. `v0.3.0-dev`) and potentially disrupt the protocol/server state as a result.

This should immediately terminate the client's connection attempt. However, there are scenarios in which you would want to connect regardless (i.e. testing with close-enough versions); to enable that, there should be an option to circumvent that check (e.g. `--skip-network-version-check`) that is only available in non-production builds.

**Comment by ten3roberts** [comment]
When implementing this (at the end of a large PR) we decided to not make it a hard fail as the version may not be consistent and as you said to not break @pierd's work when deploying and doing local fix commits that haven't been deployed. Adding an overide flag may be the best way to go about it, though if it brings a lot of false positives to begin with it is going to be a point of frustration for users where you just always enable that flag, and you are back to square one. (Can't remember the idiom for a broken safety switch that you then ignore)

It not being consistent was shown quite quickly #559

**Comment by pierd** [comment]
From my understanding the 3 ambient versions have to match:
1. one used for build + deploy
2. server running given project
3. client connecting to the server

We can have CI build and upload ambient binary for each commit. Then the backend would download ambient build for given version/commit hash when starting a server. Note that this will make the server startup slightly slower (because of the download) but it would solve 1. and 2. (assuming we are fine with the storage, currently 80-90MB/ambient binary). If we want to be more frugal with the storage then we can stick to just released builds and nightly dev builds.

3. is what is going to be painful for the most people. Although this problem won't exist with web client as we can fully control what client version is used.

**Comment by philpax** [comment]
> Adding an overide flag may be the best way to go about it, though if it brings a lot of false positives to begin with it is going to be a point of frustration for users where you just always enable that flag, and you are back to square one. 

I'm not too worried about that - this should only be applicable for developer versions, so developers should know what they're in for when they disable the check. This shouldn't be exposed in builds that users will be using. 

> Point 3. is what is going to be painful for the most people. Although this problem won't exist with web client as we can fully control what client version is used.

Yeah, our web client will be the primary client for the next while, so that shouldn't be too troublesome. In future we might have an Ambient version manager or such that will abstract over the version. (Might be a bit weird because you'll need to connect to the server to know which version it's running on, but we can probably add a HTTP endpoint or such for prospective clients to query the server)
