### ISSUE TITLE
Bool/Empty components are redundant but have different (opposite) usage

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#577]
Is there a reason we have _both_ Bool and Empty components? They have behaviour that is very similar but their usage is different in ways that are confusingly different.

**Comment by droqen** [comment]
See #576

**Comment by philpax** [comment]
They represent different things; I'm not sure it necessarily makes sense to compare them. An empty component is a component where its presence indicates some fact about the entity, while a boolean component is 'just' a binary piece of data attached to the entity with no inherent semantic meaning. A boolean component also has three states - true, false, not present - as opposed to the two of an empty component.

A more concrete example is the difference between `dont_store: Empty` and `store: Bool`; the former implies that entities are stored by default and attaching the component is a change in that behaviour, while the latter doesn't attest anything about behaviour if it's not present.

Are there any components that you think suffer from being confusing in this regard?

**Comment by droqen** [comment]
Hmm. In the `dont_store: Empty` and `store: Bool` example, I suppose I see them both as implying some default... That is, having a `store: Bool` component implies that without such a component, entities are not stored by default and [attaching the component AND setting it to true] is a change in that behaviour, while [attaching the component] makes no difference at all.

This is how I think about `ambient_physics::dynamic`. I'm not sure if I ran into this issue but definitely someone else did in the Ambient Discord if not me. That is, if you don't know whether the component is Bool or Empty, there isn't much of a functionality hint suggesting that it should be one or the other, making it a tossup between `with(component(),true)` and `with_default(component())`. If you choose wrong, you get an error or broken behaviour. Likewise, when _defining_ a new component, it seems mostly arbitrary to choose one over the other.

p.s. I've been calling it `None` above but it's `Empty`. I will have to keep that in mind.

**Comment by philpax** [comment]
> Hmm. In the `dont_store: Empty` and `store: Bool` example, I suppose I see them both as implying some default... That is, having a `store: Bool` component implies that without such a component, entities are not stored by default and [attaching the component AND setting it to true] is a change in that behaviour, while [attaching the component] makes no difference at all.

Hm, I see where you're coming from, but you could make the argument for the contrapositive - the default could be store-by-default, as it is now, in which case `with(store(), false)` (or `with_default(store())`) would result in different behaviour to the component not being attached.

It's a trade-off, but I "feel" like the `Empty` components better indicate the default state of something and that there are only two behaviours (default and not-default), as opposed to the three-that-could-be-two (not attached, off, and on, where "not attached" could correspond to off or on)

> This is how I think about `ambient_physics::dynamic`. I'm not sure if I ran into this issue but definitely someone else did in the Ambient Discord if not me. That is, if you don't know whether the component is Bool or Empty, there isn't much of a functionality hint suggesting that it should be one or the other, making it a tossup between `with(component(),true)` and `with_default(component())`. If you choose wrong, you get an error or broken behaviour. Likewise, when _defining_ a new component, it seems mostly arbitrary to choose one over the other.

Aye, `ambient_physics::dynamic` is definitely one of the more controversial ones. That was mostly because we don't have a way to do enums in components yet - otherwise, it would have been `ambient_physics::collider_type: ColliderType (Dynamic, Static)`, without a `Default` specified, so that you would be forced to pick one.

Hopefully, when enum support lands, we can clean that up and make the choice more obvious. Non-presence is still a debuggability problem, but that's something we can hopefully address with #516.

I suspect we'll do a pass over all of the existing components to make them consistent in type and structure, so that:

1) Empty components are used to indicate something different from the default state, and should generally be added once and not changed afterwards (e.g. `dont_store`)
2) Boolean components should store data that could change over the period of execution, and should generally be considered as "plain old data" (e.g. `looping`). Non-presence of a component is either a warning or behaves identically to the component being *false* (not true).
3) Components that require an actual choice are enums, so that they don't suffer from the semantic collapse of being stuffed into a boolean/integer/what have you. (e.g. `ColliderType`, `Layout`, ...)

and we'll try to codify this in the docs, so that the ecosystem generally tries to maintain this standard, too.

**Comment by droqen** [comment]
Hmm. I have a bone to pick with Empty components, but it might be better understood as a separate issue. It strikes me that an Empty component would be better rendered as a Concept, including the possibility of an Empty Concept. It's like having an empty variable... it doesn't make sense.

I completely agree with your breakdown 1/2/3, it's just that I don't think 1 really describes something component-ish.

Concept support isn't 100% yet so I'm not pushing for it to happen right away.

**Comment by droqen** [comment]
To explain my thinking here, it seems that for the most part an Empty component is going to be used in a way that's totally different from other components, and in a way that may indicate the presence/relevance of other components, e.g. `physics_controlled` is currently an Empty component that is a prerequisite(?) for the proper functioning of `dynamic` and other physics components; this more or less exactly describes what a concept is used for. In some cases we might need a concept that doesn't suggest the presence of any additional information, which is what I mean by an 'empty' concept... just a concept with no components?

That's probably not actually compatible with concepts are, since I think they're supposed to be bound to a particular group of components such that assigning all the components that happen to match a concept will make it match the concept (is that right?), but components are doing a weird double duty right now - they contain changeable information _and_ they describe functionality. Not all functionality requires changeable information. The solution of re-using the 'changeable information' structure purely as a hook for functionality just strikes me as a little bit odd.

**Comment by droqen** [comment]
Right, I understand what the empty Components are for now - they might almost be 'Concept-identifying tags' in some cases, and then Concepts are convenient filters/shorthands that allow us to parse that potentially vast ocean of Components.

I'm getting the feeling that Components are solid, but have design choices which more or less rely on a more complete conception of Concepts that is not yet implemented -- i.e. in an ideal world a developer could never touch an empty Component at all in their code, only interacting with them via Concepts, _but_ we do not yet live in that ideal world, so we have to do a bunch of that somewhat less intuitive Concept work manually for now.

For my part, I think I'll stop using `.with_default` completely, which will immediately clear up a lot of the ambiguity; I used it in the past mainly because I didn't know the syntax for assigning the empty value to components... and the only reason I didn't know the syntax was because `.with_default` was used so much ;)

**Comment by philpax** [comment]
> I'm getting the feeling that Components are solid, but have design choices which more or less rely on a more complete conception of Concepts that is not yet implemented -- i.e. in an ideal world a developer could never touch an empty Component at all in their code, only interacting with them via Concepts, _but_ we do not yet live in that ideal world, so we have to do a bunch of that somewhat less intuitive Concept work manually for now.

Yeah, I hope so. Instead of trying to intuit which components you need to add, you should hopefully be able to merge in concepts and have everything needed.

Feel free to suggest concepts that you think should be added - API-level concepts should already work for the most part, so we can get started with that and fill in the rest later.

**Comment by philpax** [comment]
The empty components have better names and we've removed `with_default` - do you think that's sufficient to close this issue out?

**Comment by droqen** [comment]
Yes, I think so! closing
