### ISSUE TITLE
Animation looping(false) is not working

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#608]
The animation will just jump to the end straight.

From the video we can see that without looping, it's buggy but the anim still plays. With looping set to false, the anim stops working.

https://github.com/AmbientRun/Ambient/assets/35621141/6238d67e-854f-4fe6-9d30-4415417aa6d7

**Comment by FredrikNoren** [comment]
So this is probably because you create those animation players upfront and start playing the animations on them immediately. You should just have one animation player per character instead. For instance to do a death effect you would then create that PlayAnimationClip _when the character dies_. Otherwise it will have finished playing long ago.

**Comment by chaosprint** [comment]
I know how it works now. But can creating PlayAnimationClip every time we need it become quite heavy?

**Comment by FredrikNoren** [comment]
@chaosprint Hm, it might be that the clips have been dropped from the asset cache and it's loading them again. You can create a bunch of PlayAnimationClip's somewhere and just keep them alive to keep the clips in memory. https://ambientrun.github.io/Ambient/reference/animations.html#pre-loading-animations
