### ISSUE TITLE
New asset pipeline error - "could not find `assets`"

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#647]
```
failed to compile, stdout: error[E0433]: failed to resolve: could not find `assets` in `boatblue_scatteredtrash`
         --> src\s_scatter_trash.rs:18:65
          |
       18 |         .with(model_from_url(), crate::boatblue_scatteredtrash::assets::url("MSH_Prop_Trashbag.glb").unwrap())
          |                                                                 ^^^^^^ could not find `assets` in `boatblue_scatteredtrash`
```

I haven't been able to repro this in a fresh project. Why am I getting this error?

https://github.com/droqen/23-08Blue/tree/main/BoatGameBlue/embers/boatblue_scatteredtrash

**Comment by philpax** [comment]
Your `ambient_api` dependency in `Cargo.toml` is from the 2nd of August:
`ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", rev = "dfc59e4c33" }`

You can change that to refer to `branch = "enum-support"` and then run `cargo update`, or you can manually update the revision.

(The API provides the macro that generates the `assets`, which is why you're seeing this.)

**Comment by philpax** [comment]
Is this still an issue after https://github.com/droqen/23-08Blue/pull/3 ?

**Comment by droqen** [comment]
Ah, no, I think this can be closed! Thank you
