### ISSUE TITLE
Rendering on Web on Windows is broken

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#651]
Something seems to be wrong on chrome on Windows with the renderer on the web

**Comment by ten3roberts** [comment]
Yes. @Pombal discovered this as well, and it has been added to my task list.

Thansk

**Comment by ten3roberts** [comment]
Though what exactly does *instance* rendering mean in this context?

Is it referring to the indirect primitives, or the `instancing` example, or something else. Afaik we don't really make use of instancing in the common sense

**Comment by FredrikNoren** [comment]
@ten3roberts I just meant the web version of ambient

**Comment by Pombal** [comment]
I narrowed it down to an issue with the Fxc shader compiler. I have side by side captures of a good and a broken build but debugging the shader assembly gets tricky because we're not comparing apples to apples, it's DXBC vs DXIL.

To repro natively change the backend to wgpu::Backends::DX12 with wgpu::Dx12Compiler::Fxc in gpu.rs.

**Comment by philpax** [comment]
For some more data, Tangent on the web on Windows works, but `a_foggy_scene` does not: it looks like this 
![image](https://github.com/AmbientRun/Ambient/assets/707827/6bb4e6a3-9d97-488e-ad37-272b38852655)
