### ISSUE TITLE
Runtime package addition

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#676]
Once you start a game with multiple embers, you can disable and reload them, but you can't add new embers. This should hopefully not be too difficult once #675 is done.

**Comment by philpax** [comment]
Thinking this through with #675. Each ember should be represented as a networked ECS entity, and there should be a networked resource that indicates how to map IDs to entities. Things that shouldn't be visible to the client can remain as unnetworked components.

This also opens up the exciting opportunity for querying embers at runtime, including getting their runtime items - their registered components, messages you can send to them (maybe some kind of "protocol" scheme), concepts, etc - and more. Full dynamic introspection!

This also means that there will be two representations of the embers: the semantic, and the runtime ember entities. Keeping them in sync will be a little annoying, but the semantic can contend with the static relationships with the embers, and the runtime can contend with the runtime relationships.

**Comment by ten3roberts** [comment]
How about another in-between approach that makes static and dynamic(runtime) embers inhabit the same level.

The static part of the ember if currently an `Ambient.toml` defining the components, messages and name, and a `Cargo.toml` and the related Rust code. How about we completely decouple them and make the `Ambient.toml` entirely inert and separate from the *code*. This way, you can statically *depend* on an ember to send messages to it, but instead of depending on the live ember you only depend on the shape of it. I suppose it is similar to a forward declaration in C.

The associated *live* guts, such as WebAssembly binaries, models, textures, etc only live in the ECS when loaded.

This way we keep the same representation between embers present at build, and embers added through a UI, which avoids the coloring problem of embers which otherwise would entail.

The caveat of this is that you can only send messages to embers which you statically depended on, as you need to depend on a ambient manifest to get the message type in rust. However, there is nothing limiting us to depending on the *full* embers as build time, we can simply provide the convenience of depending on *just* the manifest, where the actual contents are supplied when running.

This would also allow multiple different embers to provide the same functionality if they all build from the same ambient manifest. This way you can *choose* your implementation similar to how you can choose your implementation of a `handler: Box<dyn MyTrait>` by simply switching up what you supply when creating it, without having to modify anything downstream.

An example would be someone making a `pathfinder` ember, which uses a grid-based heuristic. Then someone makes a `pathfinder-bsp` by forking `pathfinder` and thus using the same `Ambient.toml`, but using a BSP accelerated pathfinding approach. Embers depending on and communicating with `pathfinder` to get paths would not need to be changed if you decide to swap it out with `pathfinder-bsp` since from the surface they are identical.

This *would* require us to separate embers and manifests at the database level, such that you can depend on a manifest only, where the actual ember_id/deployment can be decided upon at runtime. This would perhaps alleviate the publishing problem, as the embers don't need each other to build, so you can publish all the manifests first to the database, and *then* publish your embers in any order.

Looking at our users this method is already being used to some degree, where `afps` uses an empty `schema` ember to define *what* and then the *how* inside `fpsmovement` later.

Ironically, this makes us very close to the existing header->object->linker architecture, and the WIT definitions we already use for our embers :smile:. something, something great minds think alike.
