### ISSUE TITLE
`first_person_camera` parent-child position bug

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#696]
if we change the `cube` to an imported model in the `first_person_camera` example:
```rust
entity::add_components(
    id,
    Entity::new()
        .with_merge(make_transformable())
        // .with_default(cube())
        .with(prefab_from_url(), assets::url("X Bot.fbx"))
        .with_default(physics_controlled())
        .with_default(player_movement_direction())
        .with(color(), Vec4::ONE)
        .with(character_controller_height(), 2.)
        .with(character_controller_radius(), 0.5)
        .with(player_head_ref(), head)
        .with(ball_ref(), ball)
        .with(children(), vec![head])
        .with(player_pitch(), 0.0)
        .with(player_yaw(), 0.0),
);
```

the camera/head is no longer moving with the player

**Comment by philpax** [comment]
What does the debugger say about the resulting hierarchy? My guess is that `children` gets overwritten by `prefab_from_url`, so that it's no longer coupled.

**Comment by chaosprint** [comment]
> 

debugger shows the player has two children, one is the camera and the other is the model

**Comment by chaosprint** [comment]
> Can you take a server ECS dump and show the relevant slice of the hierarchy?

ok I solved it by adding a `.with_default(local_to_world())` to the player... 🤣 

would be a quite painful debugging experience for beginners

**Comment by chaosprint** [comment]
in general `local_to_parent` is very confusing.
there might be some related issues already.

**Comment by philpax** [comment]
Yeah that one's come up more often than not, I wonder what we can do about it.

@FredrikNoren do you think there would be any issues with ensuring `local_to_world` and `inv_local_to_world` exists if any of `translation`/`rotation`/`scale` exists, and ensuring that `local_to_parent` exists if `parent` exists?

**Comment by FredrikNoren** [comment]
@philpax Hm yeah I don't think that's a good idea:
- `inv_local_to_world` is not free to compute so should only exist for entities that actually need it (mostly just camera)
- `local_to_parent` can't be applied to everything with `parent`; if we do that we can't break transform hierarchy which is used for a lot of stuff (UI is basic example but also any effect where a child doesn't perfectly follow a parent is relevant)
- Automatically creating `local_to_world` for anything with `translation` etc. is maybe ok.. but it feels like we're going in the wrong direction for some reason? It feels like people should be able to use a component like `translation` without another component getting automatically attached.

@chaosprint Just to make sure, you've seen https://ambientrun.github.io/Ambient/reference/hierarchies.html right? 

I suspect that @philpax was right in this case, that it's the children getting overriden on the client side. Adding `.with_default(local_to_world())` shouldn't have any effect since you already have `make_transformable` (unless that was removed).

**Comment by philpax** [comment]
> Automatically creating `local_to_world` for anything with `translation` etc. is maybe ok.. but it feels like we're going in the wrong direction for some reason? It feels like people should be able to use a component like `translation` without another component getting automatically attached.

Is there a context in which you'd want to use the T/R/S components without needing a `local_to_world`?

> you already have `make_transformable`

fwiw `transformable` doesn't include `local_to_world`, maybe we should add it there and that might suffice instead of automatically adding LTW

**Comment by FredrikNoren** [comment]
> Is there a context in which you'd want to use the T/R/S components without needing a `local_to_world`?

Hm maybe for things that live on the server; i.e. I could set translation there and then create the ltw on the client?

> fwiw `transformable` doesn't include `local_to_world`, maybe we should add it there and that might suffice instead of automatically adding LTW

Ah didn't realize that, yeah makes sense to have it transformable.
