### ISSUE TITLE
Redesign concept API code generation

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#748]
Concepts are not seeing much use at present because the existing codegen'd interface for them - `concept() -> (Component<Ts...>)` and `make_concept() -> Entity` and `is_concept(id) -> EntityId` - is quite limited, especially when it comes to specifying values.

To quote @droqen:

> The problem with concepts is that they’re nothing but extremely limited/weak constructors. If I want something even slightly outside of a concept’s default parameters I have to get all those components in my headspace, so they don’t simplify interacting with code/components for me — and they’re so inflexible that I nearly always want something that make_{concept} can’t accomplish on its own.

After some discussion in Discord, we have a new proposal.

A concept trait:
```rust
trait Concept {
  fn make(&self) -> Entity;
  fn get(id: EntityId) -> Option<Self>;
  fn contained_by(id: EntityId);
}
impl<T: Concept> From<T> for Entity {
  fn from(concept: T) {
    concept.make()
  }
}
```

And for the following concept:
```toml
[concepts.MyCoolConcept]
a_component = 3.14
another_one = 42
```

This code is generated:
```rust
pub struct MyCoolConcept {
  pub a_component: f32,
  pub another_one: u32
}
impl Default for MyCoolConcept {
  fn default() -> Self {
    MyCoolConcept {
      a_component: 3.14,
      another_one: 42,
    }
  }
}
impl MyCoolConcept {
  // a tuple of all components, for use with queries
  pub fn tuple() -> (Component<f32>, Component<u32>) {
    (Self::a_component(), Self::another_one())
  }

  // components
  pub fn a_component() -> Component<f32> { a_component() }
  pub fn another_one() -> Component<u32> { another_one() }
}
impl Concept for MyCoolConcept {
  fn make(&self) -> Entity {
    Entity::new()
      .with(MyCoolConcept::a_component(), values.a_component)
      .with(MyCoolConcept::another_one(), values.another_one)
  }

  fn get(id: EntityId) -> Option<Self> {
    Some(Self {
      a_component: entity::get_component(id, Self::a_component())?,
      another_one: entity::get_component(id, Self::another_one())?,
    })
  }

  fn contained_by(id: EntityId) {
    entity::has_components(id, &[&Self::a_component(), &Self::another_one()])
  }
}
```

You could then use this as
```rust
let my_entity = MyCoolConcept { another_one: 1337, ..Default::default() }.make().spawn();
let my_concept = MyCoolConcept::get(my_entity).unwrap();
println!("{}", MyCoolConcept::contained_by(my_entity));
```

Potential future extensions:
- Offer a way to not specify defaults for each component. In this case, no `Default` would be generated; instead, a `new` would be generated with all of the default fields specified, and the non-default fields passed in as parameters:
  ```rust
  impl MyCoolConcept {
    fn new(another_one: u32) -> Self {
      Self { a_component: 3.14, another_one }
    }
  }
  ```
  This is not specified right now because I'm not sure what the syntax for this would be in TOML. We can't use `[]` or `{}` because those might be used by `Vec`s or other such containers. (Maybe `{}` would work - I think that's only used by `Empty`, which we can treat as normal?)
- Offer helper methods in the trait for interacting with the ECS world - instead of `entity::add_components(id, MyCoolConcept::default().make())`, it could just be `MyCoolConcept::default().add(id)`.
- Offer helper methods for constructing queries where you get a `Vec<MyCoolConcept>`. Could be convenient, but not sure if we should try to offer all the potential query variants. Maybe queries themselves can optionally take `Concept`s and convert them back?
- Concepts could have components that *can* be a part of the concept, but are not required to be. These would be represented as `Option`s.

**Comment by marceline-cramer** [comment]
looks great to me.

one other thing i'd suggest is the ability to use concepts directly in queries without needing to use component tuples and fetching concepts by hand:
```rs
// from:
query(other_component()).requires(MyConcept::tuple()).each_frame(move |entities| {
    for (e, other) in entitities {
        // retrieve MyConcept
        let my_concept = MyConcept::get(e).unwrap(); // unwrap is sketchy but will never panic
    }
});

// to:
query((other_component(), MyConcept::query()).each_frame(move |entities| {
    for (e, (other, my_concept)) in entitities {
        // my_concept is already a MyConcept :)
    }
});
```

if that doesn't work with the type system for whatever reason, adding a `from_tuple` constructor or something similar for all `Concept`s would work too:
```rs
query((other_component(), MyConcept::tuple()).each_frame(move |entities| {
    for (e, (other, my_concept)) in entitities {
        // convert from a tuple into a type-opaque struct!
       let my_concept = MyConcept::from_tuple(my_concept);
    }
});
```

Either way, you get type transparency but can get rid of the `.unwrap()`.

**Comment by philpax** [comment]
Yeah, that would be quite nice. Might require some type system hackery (the query implementation just takes in a tuple of component types at present), but I'll look into it and determine if it's possible.

**Comment by FredrikNoren** [comment]
So I think at the core of everything here is the fact that what we're starting to try to do is to provide _guarantees_ about data structure; i.e. something like a type system, or in the database world a schema.

For example, relationships are completely "untyped" now (i.e. `children: Vec<EntityId>`) which is analogous to `children: Vec<dyn Any>` in Rust.

There's a bunch of different ways that we want to set up these guarantees about data. For example: 

1. *Components A and B always go together*: i.e. the infamous `character_controller_height` and `character_controller_radius`. (For these things I suspect that exposing structs would be a better way forward rather than concepts, as they can guarantee at compile time that both data exists, always)
2. *Component B requires component A*: i.e. `physics_controlled` requires a collider. Here I'm also not entirely sure concepts are the right way (it might, but just not 100% sure). We could also allow people to specify these things on components and runtime check for it inside of the ecs. And maybe there are more ways.
3. *Typed relationships* (i.e. like above; being able to say `player_units: Vec<EntityId<Unit>>` which would guarantee something about those entities, also what I think @droqen touches on in his document)

More lose thoughts: if we had something like `EntityId<Unit>`, we could probably do an rpc like `fn create_unit(position: Vec3) -> EntityId<Unit>` which would have some guarantees (and if that's a pattern we'd encourage, or even enforce, then it could address what @droqen brought up about more complex initializations of entities). It could be enforced by automatically requiring a `create_X` to be defined in code for each concept you specify, though then we get into overload land etc..

**Comment by FredrikNoren** [comment]
In general, something also feels a bit off with concepts. I think it's because they feel like inheritance hierarchies, whereas the whole point of an ECS is to _compose_ objects from parts. I.e. with concepts it feels like we're coming closer and closer to having things like `SkeletonWarior: UnitWithAIAndHpButWithoutArmor` as a concept, which is exactly what everyone was trying to get away from.

**Comment by ten3roberts** [comment]
I agree with you as well.

For me it feels like concepts are just a solution to the underlying problem which is the number of components you need.

For example, I have under many mod jams struggled to get something physics controller and falling with gravity, as there are just so many components you need to add and configure properly. Concepts in my opinion just covers this up in a specific "physics" concept that may or may not fit your need, and strays away from the ECS design and into C++ OOP land.

I think the underlying problem is that there are too many *small* components which are too coupled, like the character controller you mentioned earlier. 

The better way forward that I have though a lot about is two-fold.

1. Enable the use of composite types for components instead of separate components which don't do anything in isolation. I.e; a `character_controller_size: CharacterControllerSize { width: f32, height: f32 }` or just `Vec2`. This way you are always guaranteed that both exists and can thus rely upon it. This is what @FredrikNoren mentioned as well. Of course, we will have the discussion of what should be coupled as a field in a struct and what should be a separate component. But I think this is easier to answer than concepts which are larger and bundle which which *do* work in isolation. Additionally, this will allow smaller tuples in the queries as that part can become quite verbose when you need both "parts".

2. Improve query capabilities to include things such as optional components, or `opt_or_default` etc to allow queries to work with sensible defaults if not all components are present. This way components such as `color` etc work as *overrides* that further specify a behavior, rather than something which needs to be added to an entity for it to work *at all*. This will both reduce the number of components you need to set up an entity, reduce the noise by focusing on values you *want* rather than values you just need present. Having an entity be lighter weight like this also reduces noise during printing, debugging. Another approach to this is having systems auto add components, but such a system where components that may be manually added also magically appear, which may lead to unexpected behaviors, especially if multiple systems are fighting over adding a component because some others were present

**Comment by ten3roberts** [comment]
My intention with `optional_or_default` is to be able to use a *components* default, such that

`query(translation(), scale().optional_or_default())` will yield `1,1,1` for all entities where you only specified a `translation`.

The same goes for color.

Additonally, this could go for physics where we opt for a sane default of boolean components, such as `dynamic: bool` and *assume* a value unless specified, rather than not iterating over the entity *at all* due to missing components

**Comment by marceline-cramer** [comment]
I for one am not sure that concepts are necessarily OOP-y. Over in Bevy Land, components can have as many fields as you want, since components can be entire structs, not just singular data types. I think that concepts would need to have negative dependencies between each other (as in, some concepts can't be combined on the same entity) in order for that to start reeking of OOP.

Another thing I want to mention is that you can still compose multiple concepts that may share some components, meaning that concepts aren't at the exclusion of each other on the fine-grained component level either.

**Comment by philpax** [comment]
Hi all!

Sorry about the slow response, it took some time to digest.

> _Components A and B always go together_: i.e. the infamous `character_controller_height` and `character_controller_radius`. (For these things I suspect that exposing structs would be a better way forward rather than concepts, as they can guarantee at compile time that both data exists, always)

That would be preferable, but it'll take a fair bit of engineering effort/time. Is there a better solution than concepts in the short-term?

> _Typed relationships_ (i.e. like above; being able to say `player_units: Vec<EntityId<Unit>>` which would guarantee something about those entities, also what I think @droqen touches on in his document)

For context, there's some discussion about this in #600. I agree that we should investigate this in more detail at some point - relational queries are very powerful and help us take ECS-as-a-database to the next level.

> More lose thoughts: if we had something like `EntityId<Unit>`, we could probably do an rpc like `fn create_unit(position: Vec3) -> EntityId<Unit>` which would have some guarantees (and if that's a pattern we'd encourage, or even enforce, then it could address what @droqen brought up about more complex initializations of entities). It could be enforced by automatically requiring a `create_X` to be defined in code for each concept you specify, though then we get into overload land etc..

Yeah, I was thinking we could introduce RPCs as a solution for complex constructors. The concepts outlined here could be used to implement simple/unambiguous construction, where an entity can be made purely from specifying component values, with RPCs used for more complex behaviour.

> In general, something also feels a bit off with concepts. I think it's because they feel like inheritance hierarchies, whereas the whole point of an ECS is to _compose_ objects from parts. I.e. with concepts it feels like we're coming closer and closer to having things like `SkeletonWarior: UnitWithAIAndHpButWithoutArmor` as a concept, which is exactly what everyone was trying to get away from.
> 
> Maybe we should consider removing the ability for concepts to inherit from each other?

The closest analogue I can think of are TypeScript interfaces - they don't confer any behaviour by themselves, but they describe the structure of data, just like concepts do. [They support extension, too](https://www.typescriptlang.org/docs/handbook/2/objects.html#extending-types).

We could remove inheritance, but the existing concepts already use it because they *do* share components - the most notable example being the cameras, which share the base camera components but offer different things on top.

> 2\. Improve query capabilities to include things such as `optional` components, or `optional_or` etc to allow queries to work with sensible defaults if not all components are present. This way components such as `color` etc work as _overrides_ that further specify a behavior, rather than something which needs to be added to an entity for it to work _at all_.

Yes, that seems quite reasonable. We can address some of the need for concepts with that - but not all, see below. That would also need #698, but that's not a huge imposition.

---

It's also worth noting that while concepts are used to provide the pieces for an entity to be driven by the host, user code can and should use them, too.

Even if we improve the queries and allow people to do similar things with their guest code, they'd still need a way of conveying the expected structure of their entities, and what you can expect from the entities they spawn.

For example, if I have a terrain spawner package that spawns terrain cells, how do I know as a consumer of that package what's present in those cells without dynamically checking?

**Comment by philpax** [comment]
Discussed this more in the office. A lot of the point of contention comes from the existence of the defaults, which force certain constraints that make things like merging concepts quite difficult (what happens when you have multiple concepts with different defaults for the same component?)

What we're thinking is, very roughly - will detail this more after lunch - is to:
- remove defaults and demote them to a suggestion that you can see in the docs for that concept / field in the struct, but leave it up to the user to specify what the value should be
- partition concepts into required and optional structures, so that you might have something like
```rust
struct Unit {
  movement_direction: Vec2,
  aim_direction: Vec3,
  optional: Option<UnitOptional>,
}

struct UnitOptional {
  walk_forward_animation_url: Option<String>,
}
```

so that you can fill in what you need, and only the components you specify will be added.

**Comment by philpax** [comment]
More office discussion: in addition to the above, structs are generated with all components for that concept and its extendees, such that:

```
Zombie:
    required:
        target: EntityId,
    extends:
        basic_character_animation
        character_movement


basic_character_animation:
    required:
        run_direction
        running
        jumping
        health
    optional:
        walk_forward_animation
        walk_backward_animation
        ...

character_movement:
    required:
        run_direction
        rotation
        vertical_velocity
        running
```

become
```rust
struct Zombie {
  target: EntityId,
  run_direction,
  running,
  jumping,
  health,
  rotation,
  vertical_velocity,
  optional: ZombieOptional,
}

#[derive(Default)]
struct ZombieOptional {
  walk_forward_animation: Option<String>,
  walk_backward_animation: Option<String>,
  // ...
}
```

However, this poses a problem: there is no way to construct a concept from the sub-concepts + the missing fields. In TypeScript, you'd still be able to do this because you can build an interface by spreading the inner concepts into the main concept: `{ ..basic_character_animation, ..character_movement, target: my_target }`. This is not possible in Rust.

As a short-term solution, we can offer an additional API generated for each Concept that takes an `Entity` and returns an `Option<Entity>` if it meets the concept, offering you a dynamic way to construct entities:

```rust
Zombie::validate_entity(
    Entity::new()
        .with_merge(
            BasicCharacterAnimation {
                ...
            }.make()
        )
        .with_merge(
            CharacterMovement {
                ...
            }.make()
        )
        .with(target(), some_entity)
).expect("Zombie is invalid").spawn()
```

An interesting future extension would be to introduce a `TypedEntity<Concept>` that encodes at construction-time that the entity has those components, and disables any operations that would break that concept. However, there are a few open questions:
- What happens if another module gets access to the raw entity and deletes those affected components?
- How does subtyping work? Can you pass a `TypedEntity<Zombie>` where `TypedEntity<BasicCharacterAnimation>` is expected?

Another direction to enable that would be to add information at runtime about the concept structure to track, but that would move concepts strictly from a tool-of-guidance to a tool-of-actual-structure, which may run counter to the flexibility we desire. (It also means entities have implicit non-component state, which is conceptually quite divergent to what we've been building so far.)
