### ISSUE TITLE
Memory leak in web version

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#864]
Repro:

1. Go to a_foggy_scene
2. Wait a while; it starts at 500mb and then just keeps climbing

**Comment by philpax** [comment]
I've had a bit of a look at this; I can't get `a_foggy_scene` working locally (I suspect it has something to do with https://github.com/AmbientRun/Ambient/commit/67c95f2eb1acd913145eb7e674acee5c565ccd25) - but I can't reproduce this running locally with any of the other games.

I'll have another look at it on Monday when things should have redeployed and stabilised a little.

**Comment by ten3roberts** [comment]
Oh, so that's why it is also failing locally for me as well.

Anyhow, to test any example with a locally built client without running (and downloading) and example is:

`cargo cf web serve`

and then join

`localhost:5173?package=a_foggy_scene` 

which will connect to a remotely running server, so it requirss your client and the target deployment to be close enough (I.e not have any new components and such breakages)

This does not require the `open-browser` SSL hack 🙌

**Comment by ten3roberts** [comment]
> I think the problem is the logs 😭

Why did I have this as a gut feeling

**Comment by philpax** [comment]
Okay, misunderstanding on my part - the debug logs are on for `web/www` (the local development client), but off for the website, where the log filter is unspecified but defaults to INFO. Think this is done, yay!
