### ISSUE TITLE
Flickering with culling

### ISSUE THREAD

**Issue by Pombal** [AmbientRun/Ambient#955]
With GPU culling, games such as Tangent flicker frequently. Consider disabling culling for the launch until we can fix properly.

**Comment by ten3roberts** [comment]
I suppose you meant *With Culling*

If so, this is an issue which has been with us on mac and other indirect rendering targets since almost the start, when the indirect culled rendered was written.

It is caused by the one frame lag of the culling results readback from the gpu, which dictates how many draw calls to issue for each material, and at which offset the material is at.

When something comes into or out of view, or the materials are changed, there is the one frame period where the issued draw calls and offsets are incorrect for the new material layouts and buffer data/count of things as the previous (or multiple frame back) offsets are used.

I've wanted to to rewrite the renderer to fix the flickering, and do instances rendering, rathe than issuing N*M draw calls for N entities with M primitives and lods.

The new renderer I have in mind would also fix our long standing issue where we can't use DX12 with multi indirect rendering, as DX12 does not support `first_instance`, this was *one* of the bugs for the windows web rendering we rediscovered.

**Comment by philpax** [comment]
Is it viable to disable culling or weaken it to hide the flickering for this release, at least?

**Comment by philpax** [comment]
https://github.com/AmbientRun/Ambient/commit/985cdb7331ac9792cb7a9cf94f6f0b097e445e37 disables it for the web, should we also do it for desktop?

**Comment by Pombal** [comment]
Done in https://github.com/AmbientRun/Ambient/commit/83b6dd107d636941583a1f14232540c0f57b5f40
